spring:
  application:
    name: account-service
  
  r2dbc:
    url: r2dbc:postgresql://localhost:5433/account_db
    username: postgres
    password: postgres
    pool:
      initial-size: 10
      max-size: 20
      
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: account-service-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: earliest

server:
  port: 8081

kafka:
  topics:
    customer-events: customer-events

logging:
  level:
    com.nttdata.account: DEBUG
    org.springframework.r2dbc: DEBUG
    org.springframework.kafka: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
